In [1]:
# Import Packages
import pandas as pd
import csv
import seaborn as sns
import numpy as np
import networkx as nx
import graphviz
from IPython.display import display
from collections import defaultdict
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, MultiLabelBinarizer, StandardScaler
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split, cross_validate
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn.ensemble import RandomForestClassifier
from sklearn import tree 
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score , roc_curve

# FETCHING DATA FROM CSV

In [2]:
df = pd.read_csv (r'final_disease_symptom_data.csv')   #read the csv file (put 'r' before the path string to address any special characters in the path, such as '\'). Don't forget to put the file name at the end of the path + ".csv"
df

Heberden's node  Murphy's sign  Stahli's line  abdomen acute  \
0                  0              0              0              0   
1                  0              0              0              0   
2                  0              0              0              0   
3                  0              0              0              0   
4                  0              0              0              0   
..               ...            ...            ...            ...   
143                0              0              0              1   
144                0              0              0              0   
145                0              0              0              0   
146                0              0              0              0   
147                0              0              0              0   

     abdominal bloating  abdominal tenderness  abnormal sensation  \
0                     0                     0                   0   
1                     0                     0                   0   
2                     0                     0                   0   
3                     0                     0                   0   
4                     0                     0                   0   
..                  ...                   ...                 ...   
143                   0                     1                   0   
144                   0                     0                   0   
145                   0                     0                   0   
146                   0                     0                   0   
147                   0                     0                   0   

     abnormally  hard consistency  abnormally hard consistency  abortion  ...  \
0                               0                            0         0  ...   
1                               0                            0         0  ...   
2                               0                            0         0  ...   
3                               0                            0         0  ...   
4                               0                            0         0  ...   
..                            ...                          ...       ...  ...   
143                             0                            0         0  ...   
144                             0                            0         0  ...   
145                             0                            0         0  ...   
146                             0                            0         0  ...   
147                             0                            0         0  ...   

     weepiness  weight gain  welt  wheelchair bound  wheezing  withdraw  \
0            0            0     0                 0         0         0   
1            0            0     0                 0         0         0   
2            1            0     0                 0         0         0   
3            1            0     0                 0         0         0   
4            0            0     0                 0         0         0   
..         ...          ...   ...               ...       ...       ...   
143          0            0     0                 0         0         0   
144          0            0     0                 0         0         0   
145          1            0     0                 0         0         0   
146          0            0     0                 0         0         0   
147          0            0     0                 0         0         0   

     worry  yellow  sputum  yellow sputum                    diseases  
0        0               0              0       hypertensive  disease  
1        0               0              0                    diabetes  
2        1               0              0          depression  mental  
3        1               0              0         depressive disorder  
4        0               0              0  coronary  arteriosclerosis  
..     ...             ...            ...

# SEPARATING SYMPTOMS AND DISEASE COLUMS

In [3]:
X = df.iloc[:,:-1]
Y = df.iloc[:,-1]

In [4]:
X

Heberden's node  Murphy's sign  Stahli's line  abdomen acute  \
0                  0              0              0              0   
1                  0              0              0              0   
2                  0              0              0              0   
3                  0              0              0              0   
4                  0              0              0              0   
..               ...            ...            ...            ...   
143                0              0              0              1   
144                0              0              0              0   
145                0              0              0              0   
146                0              0              0              0   
147                0              0              0              0   

     abdominal bloating  abdominal tenderness  abnormal sensation  \
0                     0                     0                   0   
1                     0                     0                   0   
2                     0                     0                   0   
3                     0                     0                   0   
4                     0                     0                   0   
..                  ...                   ...                 ...   
143                   0                     1                   0   
144                   0                     0                   0   
145                   0                     0                   0   
146                   0                     0                   0   
147                   0                     0                   0   

     abnormally  hard consistency  abnormally hard consistency  abortion  ...  \
0                               0                            0         0  ...   
1                               0                            0         0  ...   
2                               0                            0         0  ...   
3                               0                            0         0  ...   
4                               0                            0         0  ...   
..                            ...                          ...       ...  ...   
143                             0                            0         0  ...   
144                             0                            0         0  ...   
145                             0                            0         0  ...   
146                             0                            0         0  ...   
147                             0                            0         0  ...   

     vomiting  weepiness  weight gain  welt  wheelchair bound  wheezing  \
0           0          0            0     0                 0         0   
1           1          0            0     0                 0         0   
2           0          1            0     0                 0         0   
3           0          1            0     0                 0         0   
4           0          0            0     0                 0         0   
..        ...        ...          ...   ...               ...       ...   
143         0          0            0     0                 0         0   
144         1          0            0     0                 0         0   
145         0          1            0     0                 0         0   
146         0          0            0     0                 0         0   
147         0          0            0     0                 0         0   

     withdraw  worry  yellow  sputum  yellow sputum  
0           0      0               0              0  
1           0      0               0              0  
2           0      1               0              0  
3           0      1               0              0  
4           0      0               0              0  
..        ...    ...             ...            ...  
143         0      0               0              0  
144         0      0               0     

In [5]:
Y

0           hypertensive  disease
1                        diabetes
2              depression  mental
3             depressive disorder
4      coronary  arteriosclerosis
                  ...            
143                         ileus
144                      adhesion
145                      delusion
146                affect  labile
147              decubitus  ulcer
Name: diseases, Length: 148, dtype: object

# TRAIN TEST SPLIT & MODEL CREATION

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, train_size=0.65,test_size=0.35, random_state=42)

clf = RandomForestClassifier(n_jobs=2)
RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=0.25, n_jobs=2, oob_score=False, random_state=0,
            verbose=0, warm_start=False)


RandomForestClassifier(min_impurity_split=1e-07, n_estimators=0.25, n_jobs=2,
                       random_state=0)

In [7]:
clf = clf.fit(X_test, y_test)

In [8]:
y_pred = clf.predict(X_test) #Estimating the results in y_pred

# MODEL EVALUATION

In [9]:
from sklearn import metrics
# Model Accuracy
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9423076923076923


In [10]:
print("Precision Score : ",metrics.precision_score(y_test, y_pred, 
                                           pos_label='positive',
                                           average = 'weighted'))


print("Recall Score : ",metrics.recall_score(y_test, y_pred, 
                                           pos_label='positive',
                                           average='micro'))

print("F1 Score : ",metrics.f1_score(y_test, y_pred, 
                                           pos_label='positive',
                                           average='micro'))

Precision Score :  0.9198717948717948
Recall Score :  0.9423076923076923
F1 Score :  0.9423076923076923


c:\python\python39\lib\site-packages\sklearn\metrics\_classification.py:1295: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn("Note that pos_label (set to %r) is ignored when "
c:\python\python39\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\python\python39\lib\site-packages\sklearn\metrics\_classification.py:1295: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn("Note that pos_label (set to %r) is ignored when "
c:\python\python39\lib\site-packages\sklearn\metrics\_classification.

In [11]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, confusion_matrix


#set(y_test) - set(y_pred)
print("=== Confusion Matrix ===")
print(confusion_matrix(y_test, y_pred))
print('\n')
print("=== Classification Report ===")
print(classification_report(y_test, y_pred))
print('\n')
#print("=== All AUC Scores ===")
#print(rfc_cv_score)
#print('\n')

=== Confusion Matrix ===
[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]


=== Classification Report ===
                                       precision    recall  f1-score   support

                             adhesion       1.00      1.00      1.00         1
                       affect  labile       1.00      1.00      1.00         1
                               asthma       1.00      1.00      1.00         1
                           bacteremia       1.00      1.00      1.00         1
                    biliary  calculus       0.00      0.00      0.00         1
                     carcinoma breast       1.00      1.00      1.00         1
                    carcinoma of lung       1.00      1.00      1.00         1
                   carcinoma prostate       1.00      1.00      1.00         1
                           cellulitis       1.00      1.00      1.00         1
                        cholecys

c:\python\python39\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\python\python39\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\python\python39\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# ALLOWING MODEL TO PREDICT BASED ON SYMPTOMS

In [12]:
symptoms_dict = {}

for index, symptom in enumerate(X):
    symptoms_dict[symptom] = index

In [13]:
symptoms_dict

{"Heberden's node": 0,
 "Murphy's sign": 1,
 "Stahli's line": 2,
 'abdomen acute': 3,
 'abdominal bloating': 4,
 'abdominal tenderness': 5,
 'abnormal sensation': 6,
 'abnormally  hard consistency': 7,
 'abnormally hard consistency': 8,
 'abortion': 9,
 'abscess bacterial': 10,
 'absences finding': 11,
 'achalasia': 12,
 'ache': 13,
 'adverse effect': 14,
 'adverse reaction': 15,
 'agitation': 16,
 'air fluid level': 17,
 'alcohol binge episode': 18,
 'alcoholic withdrawal symptoms': 19,
 'ambidexterity': 20,
 'angina  pectoris': 21,
 'angina pectoris': 22,
 'anorexia': 23,
 'anosmia': 24,
 'aphagia': 25,
 'apyrexial': 26,
 'arthralgia': 27,
 'ascites': 28,
 'asterixis': 29,
 'asthenia': 30,
 'asymptomatic': 31,
 'ataxia': 32,
 'atypia': 33,
 'aura': 34,
 'awakening early': 35,
 'barking cough': 36,
 'bedridden': 37,
 'behavior hyperactive': 38,
 'behavior showing increased motor activity': 39,
 'blackout': 40,
 'blanch': 41,
 'bleeding of vagina': 42,
 'bowel sounds decreased': 43,
 '

In [14]:
#Creating input vector
input_vector = np.zeros(len(symptoms_dict))

#Inserting Symptoms
input_vector[[symptoms_dict['ache'], symptoms_dict['anosmia'], symptoms_dict['ataxia'],  symptoms_dict['bedridden']]] = 1

In [15]:
#Finding out probability matrix
clf.predict_proba([input_vector])

array([[0.  , 0.16, 0.05, 0.  , 0.  , 0.04, 0.06, 0.07, 0.  , 0.  , 0.  ,
        0.  , 0.02, 0.02, 0.  , 0.02, 0.01, 0.  , 0.05, 0.  , 0.01, 0.  ,
        0.06, 0.01, 0.02, 0.01, 0.03, 0.01, 0.01, 0.02, 0.  , 0.01, 0.01,
        0.02, 0.  , 0.04, 0.01, 0.  , 0.04, 0.01, 0.02, 0.  , 0.  , 0.03,
        0.  , 0.  , 0.02, 0.  , 0.05, 0.03, 0.  , 0.03]])

# DISEASE ACCORDING TO OUR MODEL

In [16]:
clf.predict([input_vector])

array(['affect  labile'], dtype=object)